runtime: nodejs12

env_variables:
  INSTANCE_CONNECTION_NAME: INSTANCE_CONNECTION_NAME
  DB_USER: YOUR_SQL_DATABASE
  DB_DATABASE: YOUR_SQL_USER
  DB_PASS: YOUR_SQL_PASSWORD
beta_settings:
  cloud_sql_instances: INSTANCE_CONNECTION_NAME